# Set build language to Python
language: python

# Set python version to 3.6
python: 3.6

# Install dependencies
install:
  - pip install -r requirements.txt

# Run tests
script:
  - echo "hello, travis"
  
