# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: GITHUB envs
      run: |
        echo "GITHUB_SHA is ${GITHUB_SHA}"
        echo "GITHUB_REF is ${GITHUB_REF}"
        echo "GITHUB_EVENT_NAME is ${GITHUB_EVENT_NAME}"
        echo "GITHUB_EVENT_PATH is ${GITHUB_EVENT_PATH}"
        echo "GITHUB_REPOSITORY is ${GITHUB_REPOSITORY}"
        echo "GITHUB_ACTOR is ${GITHUB_ACTOR}"
        echo "GITHUB_ACTION is ${GITHUB_ACTION}"
        echo "GITHUB_RUN_ID is ${GITHUB_RUN_ID}"
        echo "GITHUB_RUN_NUMBER is ${GITHUB_RUN_NUMBER}"
        echo "GITHUB_WORKFLOW is ${GITHUB_WORKFLOW}"
        echo "GITHUB_WORKSPACE is ${GITHUB_WORKSPACE}"
      
    - name: webhook vars
      run: |
        cat ${GITHUB_EVENT_PATH}
        
    - name: context - github
      run: |
        echo "github is ${{github}}"
        echo "github.event is ${{github.event}}"
        echo "github.workflow is ${{github.workflow}}"
        
    - name: context - job
      run: |
        echo "job.status is ${{job.status}}"
        echo "job.container.id is ${{job.container.id}}"
        echo "job.container.network is ${{job.container.network}}"


  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - run: echo "hello"; ls -l
