# This is a basic workflow to help you get started with Actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '**'
  pull_request_target:
    branches:
      - 'master'
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: 查看文件
      run: ls -l

    # Runs a set of commands using the runners shell
    - name: GITHUB envs
      id: envs
      run: |
        echo "GITHUB_SHA is ${GITHUB_SHA}"
        echo "GITHUB_REF is ${GITHUB_REF}"
        echo "GITHUB_EVENT_NAME is ${GITHUB_EVENT_NAME}"
        echo "GITHUB_EVENT_PATH is ${GITHUB_EVENT_PATH}"
        echo "GITHUB_REPOSITORY is ${GITHUB_REPOSITORY}"
        echo "GITHUB_ACTOR is ${GITHUB_ACTOR}"
        echo "GITHUB_ACTION is ${GITHUB_ACTION}"
        echo "GITHUB_RUN_ID is ${GITHUB_RUN_ID}"
        echo "GITHUB_RUN_NUMBER is ${GITHUB_RUN_NUMBER}"
        echo "GITHUB_WORKFLOW is ${GITHUB_WORKFLOW}"
        echo "GITHUB_WORKSPACE is ${GITHUB_WORKSPACE}"
        echo "GITHUB_TOKEN is ${GITHUB_TOKEN}"
        echo "==========================="
        echo "my TEST_PWD is ${{secrets.TEST_PWD}}" > "test.txt"
        cat test.txt
        
        echo "::set-output name=a::${{secrets.TEST_PWD}}"
        
        echo "==========================="
        echo "github.head_ref is ${{ github.head_ref }}"
        
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: test.txt
    - name: webhook vars
      run: |
        cat ${GITHUB_EVENT_PATH}
        
    - name: context - github
      run: |
        echo "github is ${{github}}"
        echo "github.event is ${{github.event}}"
        echo "github.workflow is ${{github.workflow}}"
        
    - name: context - job
      run: |
        echo "job.status is ${{job.status}}"
        echo "job.container.id is ${{job.container.id}}"
        echo "job.container.network is ${{job.container.network}}"
      if: ${{ job.status }} == 'success' && ${{ github.workflow }} == 'main'
        
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"


  test:
    runs-on: ubuntu-latest
    name: test
    needs: build
    steps:
      - run: |
          echo "hello"
          ls -l
          echo " needs.build.steps.envs.outputs.a is ${{ needs.build.steps.envs.outputs.a }}"
      
        
  commentOnNewIssues:
    name: Comment On New Issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment On New Issues
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "Hello World1" number 1
