name: use concurrency_1

concurrency: ${{ github.ref }}


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - .github/workflows/concurrency_1.yml
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/concurrency_1.yml
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
          echo "hello concurrency_1.yml"
          sleep 10s
